// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"Dashboard","path":"/dashboard","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"首页","path":"/home","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"账户","path":"/accounts","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"产品","path":"/products","parentId":"ant-design-pro-layout","id":"5"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Accounts__index" */'@/pages/Accounts/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Products__index" */'@/pages/Products/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'C:/Users/bambo/Documents/Projects/vibe-test/frontend/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
