// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"Dashboard","path":"/dashboard","icon":"dashboard","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"录入（事实）","path":"/entry","icon":"edit","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/entry","redirect":"/entry/snapshots","parentId":"3","id":"4"},"5":{"name":"资产快照","path":"/entry/snapshots","parentId":"3","id":"5"},"6":{"name":"主数据","path":"/master","icon":"database","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/master","redirect":"/master/accounts","parentId":"6","id":"7"},"8":{"name":"账户","path":"/master/accounts","parentId":"6","id":"8"},"9":{"name":"产品","path":"/master/products","parentId":"6","id":"9"},"10":{"path":"/products/:id","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Snapshots__Entry" */'@/pages/Snapshots/Entry.tsx')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Accounts__index" */'@/pages/Accounts/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Products__index" */'@/pages/Products/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Products__Detail" */'@/pages/Products/Detail.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'C:/Users/bambo/Documents/Projects/vibe-test/frontend/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
