// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from 'C:/Users/bambo/Documents/Projects/vibe-test/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import EditOutlined from 'C:/Users/bambo/Documents/Projects/vibe-test/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/EditOutlined';
import DatabaseOutlined from 'C:/Users/bambo/Documents/Projects/vibe-test/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DatabaseOutlined';
export default { DashboardOutlined, EditOutlined, DatabaseOutlined };
