// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from 'C:/Users/bambo/Documents/Projects/vibe-test/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import AccountBookOutlined from 'C:/Users/bambo/Documents/Projects/vibe-test/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AccountBookOutlined';
import BarChartOutlined from 'C:/Users/bambo/Documents/Projects/vibe-test/frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
export default { DashboardOutlined, AccountBookOutlined, BarChartOutlined };
